# Generated by Django 2.1.1 on 2018-09-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180925_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Character'),
        ),
    ]
